[tool.poetry]
name = "agl-home-django"
version = "0.1.0"
description = ""
authors = ["Thomas J. Lux"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python =  "^3.11"
# Django = "^5.0.1"
# opencv-python = "~4"
# ffmpeg-python = "^0.2.0"
python-dotenv = "^1.0.1"
pillow = "^10.2.0"
endo-reg-db = "^0.1.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

