"""
Django settings for agl_home_django project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
from os import environ
from .base import *
from .yaml_path import yaml_path
import yaml

# Read yaml file
with open(yaml_path) as file:
    yaml_data = yaml.load(file, Loader=yaml.FullLoader)

    # Set environment variables
    for key, value in yaml_data.items():
        environ[key] = value

# Load environment variables from .env file
# The .env file should be located in the same directory as this settings file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

DEV_ENV = environ.get('DEV_ENV')
DEBUG = DEV_ENV

# We load the secret key from the environment to not have it in /nix/store.
SECRET_KEY=environ.get('SECRET_KEY')

# The static root will be a path under /nix/store/ which we don't know yet.
STATIC_ROOT=environ.get('STATIC_ROOT')

# Allowed hosts are provided via nix config
ALLOWED_HOSTS = list(environ.get('ALLOWED_HOSTS', default='').split(','))

# Application definition
ROOT_URLCONF = 'agl_home_django.urls'
WSGI_APPLICATION = 'agl_home_django.wsgi.application'

if DEV_ENV:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            # IMPLEMENT POSTGRES
        }
    }


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases




# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
